// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "GETリクエストに対して{\"message\": \"Hello, World!\"}を返す",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hello"
                ],
                "summary": "Hello Worldのエンドポイント",
                "operationId": "helloWorld",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/goals": {
            "get": {
                "description": "ユーザーの現在の目標を確認する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "現在の目標を確認するエンドポイント",
                "operationId": "checkGoal",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GoalResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/plans/accept": {
            "post": {
                "description": "ユーザーが提案されたデイリープランを受け入れる",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plans"
                ],
                "summary": "提案されたデイリープランを受け入れるエンドポイント",
                "operationId": "acceptSuggestedPlans",
                "parameters": [
                    {
                        "description": "受け入れリクエストのボディ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.AcceptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.AcceptResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/plans/suggest": {
            "post": {
                "description": "ユーザーが設定した目標とタスクに基づいて日々のお手伝いプランを生成する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plans"
                ],
                "summary": "日々のお手伝いプランを生成するエンドポイント",
                "operationId": "suggestDailyPlans",
                "parameters": [
                    {
                        "description": "提案リクエストのボディ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.SuggestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SuggestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httputil.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        },
        "main.AcceptRequest": {
            "type": "object",
            "properties": {
                "plans_ids_id": {
                    "type": "integer"
                },
                "tasks_ids_id": {
                    "type": "integer"
                }
            }
        },
        "main.AcceptResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "main.GoalResponse": {
            "type": "object",
            "properties": {
                "goal": {
                    "type": "string"
                },
                "goal_points": {
                    "type": "integer"
                }
            }
        },
        "main.SuggestRequest": {
            "type": "object",
            "properties": {
                "goal": {
                    "type": "string"
                },
                "goal_points": {
                    "type": "integer"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Task"
                    }
                }
            }
        },
        "main.SuggestResponse": {
            "type": "object",
            "properties": {
                "plans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.SuggestedPlan"
                    }
                }
            }
        },
        "main.SuggestedPlan": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "integer"
                },
                "plans_today": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Task"
                    }
                }
            }
        },
        "main.Task": {
            "type": "object",
            "properties": {
                "point": {
                    "type": "integer"
                },
                "task": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "okane no kyouiku API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
