basePath: /api/v1
definitions:
  main.SuggestRequest:
    properties:
      goal:
        type: string
      goal_points:
        type: integer
      tasks:
        items:
          $ref: '#/definitions/main.Task'
        type: array
    type: object
  main.SuggestResponse:
    properties:
      plans:
        items:
          $ref: '#/definitions/main.SuggestedPlan'
        type: array
    type: object
  main.SuggestedPlan:
    properties:
      day:
        type: integer
      plans_today:
        items:
          $ref: '#/definitions/main.Task'
        type: array
    type: object
  main.Task:
    properties:
      point:
        type: integer
      task:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: okane no kyouiku API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: 'GETリクエストに対して{"message": "Hello, World!"}を返す'
      operationId: helloWorld
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hello Worldのエンドポイント
      tags:
      - hello
  /api/v1/plans/suggest:
    post:
      consumes:
      - application/json
      description: ユーザーが設定した目標とタスクに基づいて日々のお手伝いプランを生成する
      operationId: suggestDailyPlans
      parameters:
      - description: 提案リクエストのボディ
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.SuggestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SuggestResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 日々のお手伝いプランを生成するエンドポイント
      tags:
      - plans
swagger: "2.0"
