basePath: /
definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  main.AcceptRequest:
    properties:
      plans_ids_id:
        type: integer
      tasks_ids_id:
        type: integer
    type: object
  main.AcceptResponse:
    properties:
      message:
        type: string
    type: object
  main.GoalResponse:
    properties:
      goal:
        type: string
      goal_points:
        type: integer
    type: object
  main.SuggestRequest:
    properties:
      goal:
        type: string
      goal_points:
        type: integer
      tasks:
        items:
          $ref: '#/definitions/main.Task'
        type: array
    type: object
  main.SuggestResponse:
    properties:
      plans:
        items:
          $ref: '#/definitions/main.SuggestedPlan'
        type: array
    type: object
  main.SuggestedPlan:
    properties:
      day:
        type: integer
      plans_today:
        items:
          $ref: '#/definitions/main.Task'
        type: array
    type: object
  main.Task:
    properties:
      point:
        type: integer
      task:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: okane no kyouiku API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: 'GETリクエストに対して{"message": "Hello, World!"}を返す'
      operationId: helloWorld
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Hello Worldのエンドポイント
      tags:
      - hello
  /api/v1/goals:
    get:
      consumes:
      - application/json
      description: ユーザーの現在の目標を確認する
      operationId: checkGoal
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.GoalResponse'
      summary: 現在の目標を確認するエンドポイント
      tags:
      - goals
  /api/v1/plans/accept:
    post:
      consumes:
      - application/json
      description: ユーザーが提案されたデイリープランを受け入れる
      operationId: acceptSuggestedPlans
      parameters:
      - description: 受け入れリクエストのボディ
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.AcceptRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.AcceptResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: 提案されたデイリープランを受け入れるエンドポイント
      tags:
      - plans
  /api/v1/plans/suggest:
    post:
      consumes:
      - application/json
      description: ユーザーが設定した目標とタスクに基づいて日々のお手伝いプランを生成する
      operationId: suggestDailyPlans
      parameters:
      - description: 提案リクエストのボディ
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.SuggestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SuggestResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: 日々のお手伝いプランを生成するエンドポイント
      tags:
      - plans
swagger: "2.0"
