basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: okane no kyouiku API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 'Pingへのリクエストに対してJSON形式で{"message": "pong"}を返す'
      operationId: ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Pingのエンドポイント
      tags:
      - ping
swagger: "2.0"
