basePath: /
definitions:
  controllers.GoalAndTasks:
    properties:
      goal:
        $ref: '#/definitions/models.Goal'
      tasks:
        items:
          $ref: '#/definitions/models.Task'
        type: array
    type: object
  controllers.GoalResponse:
    properties:
      goal:
        $ref: '#/definitions/models.Goal'
    type: object
  controllers.SuggestRequest:
    properties:
      goal:
        $ref: '#/definitions/models.Goal'
      tasks:
        items:
          $ref: '#/definitions/models.Task'
        type: array
    type: object
  controllers.SuggestResponse:
    properties:
      plans:
        items:
          $ref: '#/definitions/models.SuggestedPlan'
        type: array
    type: object
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  main.AcceptRequest:
    properties:
      plans_ids_id:
        type: integer
      tasks_ids_id:
        type: integer
    type: object
  main.AdjustmentResponse:
    properties:
      adjusted_plans:
        items:
          $ref: '#/definitions/models.SuggestedPlan'
        type: array
      message:
        type: string
    type: object
  main.GetDailyPlansRequest:
    properties:
      day:
        type: integer
    type: object
  main.GoalResponse:
    properties:
      goal:
        type: string
      goal_points:
        type: integer
    type: object
  main.OkResponse:
    properties:
      message:
        type: string
    type: object
  main.PointsResponse:
    properties:
      points:
        type: integer
    type: object
  main.SubmitRequest:
    properties:
      day:
        type: integer
      total_points:
        type: integer
    type: object
  models.DailyPlansResponse:
    properties:
      day:
        type: integer
      plans_today:
        items:
          $ref: '#/definitions/models.Task'
        type: array
    type: object
  models.Goal:
    properties:
      name:
        type: string
      point:
        type: integer
    type: object
  models.Plan:
    properties:
      day:
        type: integer
      tasks_today:
        items:
          $ref: '#/definitions/models.Task'
        type: array
    type: object
  models.SuggestedPlan:
    properties:
      day:
        type: integer
      plans_today:
        items:
          $ref: '#/definitions/models.Task'
        type: array
    type: object
  models.Task:
    properties:
      name:
        type: string
      point:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: okane no kyouiku API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: 'GETリクエストに対して{"message": "Hello, World!"}を返す'
      operationId: helloWorld
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Hello Worldのエンドポイント
      tags:
      - hello
  /api/v1/goals:
    get:
      consumes:
      - application/json
      description: ユーザーの現在の目標を確認する
      operationId: checkGoal
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.GoalResponse'
      summary: 現在の目標を確認するエンドポイント
      tags:
      - goals
    post:
      consumes:
      - application/json
      description: Set a goal with associated tasks
      operationId: SetGoal
      parameters:
      - description: Goal and Tasks object
        in: body
        name: goal
        required: true
        schema:
          $ref: '#/definitions/controllers.GoalAndTasks'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Set a goal with tasks
      tags:
      - goals
  /api/v1/plans/accept:
    post:
      consumes:
      - application/json
      description: ユーザーが提案されたデイリープランを受け入れる
      operationId: acceptSuggestedPlans
      parameters:
      - description: 受け入れリクエストのボディ
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.AcceptRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.OkResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: 提案されたデイリープランを受け入れるエンドポイント
      tags:
      - plans
  /api/v1/plans/check:
    get:
      consumes:
      - application/json
      description: ユーザーのデイリープランが順調かどうかを確認する
      operationId: checkProgress
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.AdjustmentResponse'
      summary: デイリープランが順調かどうかを確認するエンドポイント
      tags:
      - plans
  /api/v1/plans/submit:
    post:
      consumes:
      - application/json
      description: ユーザーがデイリータスクデータを提出する
      operationId: submitDailyTasks
      parameters:
      - description: 提出リクエストのボディ
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.SubmitRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.OkResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: デイリータスクデータを提出するエンドポイント
      tags:
      - submit
  /api/v1/plans/suggested:
    get:
      description: Get a list of suggested plans
      operationId: GetSuggestedPlans
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Plan'
            type: array
      summary: Get suggested plans
      tags:
      - plans
  /api/v1/plans/today:
    post:
      consumes:
      - application/json
      description: ユーザーが指定した日のデイリープランを取得する
      operationId: getDailyPlansOld
      parameters:
      - description: 取得する日の番号
        in: body
        name: day
        required: true
        schema:
          $ref: '#/definitions/main.GetDailyPlansRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DailyPlansResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: 指定された日のデイリープランを取得するエンドポイント
      tags:
      - plans
  /api/v1/points:
    get:
      consumes:
      - application/json
      description: ユーザーの現在のポイントを取得する
      operationId: getUserPoints
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PointsResponse'
      summary: ユーザーのポイントを取得するエンドポイント
      tags:
      - points
  /api/v2/goals:
    get:
      consumes:
      - application/json
      description: Get a list of goals
      operationId: GetGoal
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.GoalResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get goals
      tags:
      - goals
  /api/v2/plans/suggest:
    post:
      consumes:
      - application/json
      description: ユーザーが設定した目標とタスクに基づいて日々のお手伝いプランを生成する
      operationId: suggestDailyPlans
      parameters:
      - description: 提案リクエストのボディ
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.SuggestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuggestResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: 日々のお手伝いプランを生成するエンドポイント
      tags:
      - plans
  /api/v2/plans/today:
    get:
      consumes:
      - application/json
      description: ユーザーが指定した日のデイリープランを取得する
      operationId: GetTodayPlans
      parameters:
      - description: 取得する日の番号
        in: query
        name: day
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DailyPlansResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: 指定された日のデイリープランを取得するエンドポイント
      tags:
      - plans
swagger: "2.0"
